name: sports_app
description: A Flutter mobile app for athlete performance tracking.
publish_to: 'none' # remove this if you want to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & charts
  fl_chart: ^1.1.1

  # Cupertino (iOS style icons)
  cupertino_icons: ^1.0.6

  # Firebase packages
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6   # 

  intl: ^0.20.2

  flutter_riverpod: ^3.2.1

  

  # Image picker for selecting profile pictures
  image_picker: ^1.0.7       


  google_generative_ai: ^0.4.7  
  http: ^1.6.0
  provider: ^6.1.5+1

  # If you want to test Supabase later, keep this line
  # supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true